In [1]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
# nltk.download('stopwords')
from nltk.stem import PorterStemmer

df = pd.read_csv(
    "../data/raw/twitter_training.csv",
     header=None,
    names=["tweet_id","entity","sentiment","tweet"]
    )

df.head()

,tweet_id,entity,sentiment,tweet
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...

In [2]:
def clean_text(text):
    text = text.lower()                 # lowercase
    text = re.sub(r'@\w+', '', text)    # remove @user
    text = re.sub(r'#', '', text)       # remove hashtag symbol
    text = re.sub(r'http\S+', '', text) # remove links
    text = re.sub(r'[^a-zA-Z ]', '', text)  # remove special chars
    text = re.sub(r'\s+', ' ', text)    # extra spaces
    return text.strip()

In [3]:
df['clean_tweet']=df['tweet'].astype(str).apply(clean_text)
df[['tweet','clean_tweet']].head(10)

,tweet,clean_tweet
0,im getting on borderlands and i will murder yo...,im getting on borderlands and i will murder yo...
1,I am coming to the borders and I will kill you...,i am coming to the borders and i will kill you...
2,im getting on borderlands and i will kill you ...,im getting on borderlands and i will kill you all
3,im coming on borderlands and i will murder you...,im coming on borderlands and i will murder you...
4,im getting on borderlands 2 and i will murder ...,im getting on borderlands and i will murder yo...
5,im getting into borderlands and i can murder y...,im getting into borderlands and i can murder y...
6,So I spent a few hours making something for fu...,so i spent a few hours making something for fu...
7,So I spent a couple of hours doing something f...,so i spent a couple of hours doing something f...
8,So I spent a few hours doing something for fun...,so i spent a few hours doing something for fun...
9,So I spent a few hours making something for fu...,so i spent a few hours making something for fu...

STOPWORDS REMOVING

In [4]:
stop_words=set(stopwords.words('english'))
print(list(stop_words)[:10])

['and', "shouldn't", 'them', 'be', 'mightn', 'not', "won't", 'an', 'while', "we've"]

In [5]:
def remove_stopwords(text):
    words=text.split()
    filtered=[word for word in words if word not in stop_words]
    return " ".join(filtered)

In [6]:
df['clean_tweet']=df['clean_tweet'].apply(remove_stopwords)
df[['tweet','clean_tweet']].head()

,tweet,clean_tweet
0,im getting on borderlands and i will murder yo...,im getting borderlands murder
1,I am coming to the borders and I will kill you...,coming borders kill
2,im getting on borderlands and i will kill you ...,im getting borderlands kill
3,im coming on borderlands and i will murder you...,im coming borderlands murder
4,im getting on borderlands 2 and i will murder ...,im getting borderlands murder

STEMMING

In [7]:
stemmer=PorterStemmer()

def stem_text(text):
    words=text.split()
    stemmed_words=[stemmer.stem(word) for word in words]
    return " ".join(stemmed_words)

In [8]:
df['clean_tweet']= df['clean_tweet'].apply(stem_text)

In [9]:
df[['tweet', 'clean_tweet']].head(5)

,tweet,clean_tweet
0,im getting on borderlands and i will murder yo...,im get borderland murder
1,I am coming to the borders and I will kill you...,come border kill
2,im getting on borderlands and i will kill you ...,im get borderland kill
3,im coming on borderlands and i will murder you...,im come borderland murder
4,im getting on borderlands 2 and i will murder ...,im get borderland murder

In [10]:
(df['clean_tweet'].str.len() == 0).sum()

np.int64(1707)

In [11]:
df[df['clean_tweet'].str.len() == 0]

,tweet_id,entity,sentiment,tweet,clean_tweet
11,2402,Borderlands,Positive,was,
53,2409,Borderlands,Neutral,all,
60,2411,Borderlands,Neutral,. . [,
62,2411,Borderlands,Neutral,.. [,
63,2411,Borderlands,Neutral,.. 45,
...,...,...,...,...,...
74511,9172,Nvidia,Positive,@NVIDIAGeForce ],
74591,9185,Nvidia,Neutral,you,
74597,9186,Nvidia,Positive,from,
74621,9190,Nvidia,Positive,were,
74654,9196,Nvidia,Negative,??????????????????????????????????????????????...,

In [12]:
df = df[df['clean_tweet'].str.len() > 0]
(df['clean_tweet'].str.len() == 0).sum()

np.int64(0)

In [13]:
df[df['clean_tweet'].isna()].head()
df = df.dropna(subset=['clean_tweet'])
print(df.shape)

(72975, 5)

In [14]:
print(df['clean_tweet'].isna().sum())
df = df.dropna(subset=['clean_tweet'])
print(df.shape)

0
(72975, 5)

In [15]:
df.to_csv("../data/processed/clean_twitter_training.csv", index=False)

In [16]:


print(df['clean_tweet'].isna().sum())

0