In [7]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
# nltk.download('stopwords')
from nltk.stem import PorterStemmer

df = pd.read_csv("../data/raw/twitter.csv")

In [11]:
def clean_text(text):
    text = text.lower()                 # lowercase
    text = re.sub(r'@\w+', '', text)    # remove @user
    text = re.sub(r'#', '', text)       # remove hashtag symbol
    text = re.sub(r'http\S+', '', text) # remove links
    text = re.sub(r'[^a-zA-Z ]', '', text)  # remove special chars
    text = re.sub(r'\s+', ' ', text)    # extra spaces
    return text.strip()

In [12]:
df['clean_tweet']=df['tweet'].apply(clean_text)
df[['tweet','clean_tweet']].head(10)

,tweet,clean_tweet
0,@user when a father is dysfunctional and is s...,when a father is dysfunctional and is so selfi...
1,@user @user thanks for #lyft credit i can't us...,thanks for lyft credit i cant use cause they d...
2,bihday your majesty,bihday your majesty
3,#model i love u take with u all the time in ...,model i love u take with u all the time in ur
4,factsguide: society now #motivation,factsguide society now motivation
5,[2/2] huge fan fare and big talking before the...,huge fan fare and big talking before they leav...
6,@user camping tomorrow @user @user @user @use...,camping tomorrow danny
7,the next school year is the year for exams.ð...,the next school year is the year for exams can...
8,we won!!! love the land!!! #allin #cavs #champ...,we won love the land allin cavs champions clev...
9,@user @user welcome here ! i'm it's so #gr...,welcome here im its so gr

STOPWORDS REMOVING

In [13]:
stop_words=set(stopwords.words('english'))
print(list(stop_words)[:10])

['wasn', 'against', 'its', "should've", 't', "aren't", 'during', "it'd", 'mustn', 'hasn']

In [14]:
def remove_stopwords(text):
    words=text.split()
    filtered=[word for word in words if word not in stop_words]
    return " ".join(filtered)

In [15]:
df['clean_tweet']=df['clean_tweet'].apply(remove_stopwords)
df[['tweet','clean_tweet']].head()

,tweet,clean_tweet
0,@user when a father is dysfunctional and is s...,father dysfunctional selfish drags kids dysfun...
1,@user @user thanks for #lyft credit i can't us...,thanks lyft credit cant use cause dont offer w...
2,bihday your majesty,bihday majesty
3,#model i love u take with u all the time in ...,model love u take u time ur
4,factsguide: society now #motivation,factsguide society motivation

STEMMING

In [16]:
stemmer=PorterStemmer()

def stem_text(text):
    words=text.split()
    stemmed_words=[stemmer.stem(word) for word in words]
    return " ".join(stemmed_words)

In [19]:
df['clean_tweet']= df['clean_tweet'].apply(stem_text)

In [21]:
df[['tweet', 'clean_tweet']].head(5)

,tweet,clean_tweet
0,@user when a father is dysfunctional and is s...,father dysfunct selfish drag kid dysfunct run
1,@user @user thanks for #lyft credit i can't us...,thank lyft credit cant use caus dont offer whe...
2,bihday your majesty,bihday majesti
3,#model i love u take with u all the time in ...,model love u take u time ur
4,factsguide: society now #motivation,factsguid societi motiv

In [22]:
(df['clean_tweet'].str.len() == 0).sum()

np.int64(32)

In [23]:
df[df['clean_tweet'].str.len() == 0]

,id,label,tweet,clean_tweet
1961,1962,0,@user same ððð,
3351,3352,0,what i doð,
3982,3983,0,@user then why are you,
4411,4412,0,no 1 is up,
4799,4800,0,@user @user @user @user @user @user @user @us...,
5028,5029,0,@user as you should.,
5235,5236,0,@user @user @user @user @user @user @user @us...,
5309,5310,0,beð ð@user @user @user @user @user @user...,
7222,7223,0,be with who you are!,
7939,7940,0,@user why you so ðð,
9034,9035,0,@user very ...,
10461,10462,0,out and about ðâ¤ï¸,
11586,11587,0,@user and me?....,
11852,11853,1,"@user no, we're not",
11882,11883,0,@user it's at $7.25,
13038,13039,0,why so : d,
13287,13288,0,@user this is me,
13848,13849,0,@user beð ð@user @user @user @user @use...,
13862,13863,0,@user so just,
15434,15435,0,ðð» that is all....,
15494,15495,0,@user @user me to!,
16082,16083,1,@user then what is it?,
16250,16251,0,as you should.,
16320,16321,0,@user @user ð very,
18032,18033,0,@user 1d won,
19085,19086,0,@user @user only 4 in 10?,
20261,20262,0,very very very,
21970,21971,0,@user not to me.,
23514,23515,0,it was in 2008,
25629,25630,1,you me too ððððð ð¹,
28513,28514,0,@user @user @user to be here,
31781,31782,0,we are too!,

In [25]:
df = df[df['clean_tweet'].str.len() > 0]
(df['clean_tweet'].str.len() == 0).sum()

np.int64(0)

In [26]:
df.to_csv("../data/processed/clean_twitter.csv", index=False)